"""
Decision Tree Model - Trained on UCI Bank Marketing Dataset
Features: 20
Classes: 0 (No Subscription), 1 (Subscription)
"""
import numpy as np
import pickle
import base64

# Model weights and parameters saved as base64-encoded pickle
MODEL_PICKLE_B64 = "gAWVYg0AAAAAAACMFXNrbGVhcm4udHJlZS5fY2xhc3Nlc5SMFkRlY2lzaW9uVHJlZUNsYXNzaWZpZXKUk5QpgZR9lCiMCWNyaXRlcmlvbpSMBGdpbmmUjAhzcGxpdHRlcpSMBGJlc3SUjAltYXhfZGVwdGiUTowRbWluX3NhbXBsZXNfc3BsaXSUSwKMEG1pbl9zYW1wbGVzX2xlYWaUSwGMGG1pbl93ZWlnaHRfZnJhY3Rpb25fbGVhZpRHAAAAAAAAAACMDG1heF9mZWF0dXJlc5ROjA5tYXhfbGVhZl9ub2Rlc5ROjAxyYW5kb21fc3RhdGWUSyqMFW1pbl9pbXB1cml0eV9kZWNyZWFzZZRHAAAAAAAAAACMDGNsYXNzX3dlaWdodJROjAljY3BfYWxwaGGURwAAAAAAAAAAjA1tb25vdG9uaWNfY3N0lE6MDm5fZmVhdHVyZXNfaW5flEsUjApuX291dHB1dHNflEsBjAhjbGFzc2VzX5SME251bXB5Ll9jb3JlLm51bWVyaWOUjAtfZnJvbWJ1ZmZlcpSTlCiWCAAAAAAAAAAAAAAAAQAAAJSMBW51bXB5lIwFZHR5cGWUk5SMAmk0lImIh5RSlChLA4wBPJROTk5K/////0r/////SwB0lGJLAoWUjAFDlHSUUpSMCm5fY2xhc3Nlc1+UjBZudW1weS5fY29yZS5tdWx0aWFycmF5lIwGc2NhbGFylJOUaB2MAmk4lImIh5RSlChLA2ghTk5OSv////9K/////0sAdJRiQwgCAAAAAAAAAJSGlFKUjA1tYXhfZmVhdHVyZXNflEsUjAV0cmVlX5SMEnNrbGVhcm4udHJlZS5fdHJlZZSMBFRyZWWUk5RLFGgZKJYIAAAAAAAAAAIAAAAAAAAAlGgtSwGFlGgkdJRSlEsBh5RSlH2UKGgJSwaMCm5vZGVfY291bnSUSx2MBW5vZGVzlGgZKJZABwAAAAAAAAEAAAAAAAAAGgAAAAAAAAASAAAAAAAAAAAAAACXUe8/AAAAAAAA4D9QAAAAAAAAAAAAAAAAAFRAAQAAAAAAAAACAAAAAAAAABMAAAAAAAAAEwAAAAAAAAAAAABgK0vcP6zokLsvI98/QwAAAAAAAAAAAAAAAMBQQAEAAAAAAAAAAwAAAAAAAAAIAAAAAAAAAAwAAAAAAAAAAAAAsBJ5tz/Y6tkhcGPZPywAAAAAAAAAAAAAAAAARkAAAAAAAAAAAAQAAAAAAAAABQAAAAAAAAAAAAAAAAAAAAAAAFjiJfG/hIXqzBcPxj8VAAAAAAAAAAAAAAAAADVAAAAAAAAAAAD//////////////////////v////////8AAAAAAAAAwAAAAAAAAAAAAQAAAAAAAAAAAAAAAADwPwAAAAAAAAAABgAAAAAAAAAHAAAAAAAAAAYAAAAAAAAAAAAAUFPJ/T9QuB6F61G4PxQAAAAAAAAAAAAAAAAANEABAAAAAAAAAP/////////////////////+/////////wAAAAAAAADAAAAAAAAAAAATAAAAAAAAAAAAAAAAADNAAAAAAAAAAAD//////////////////////v////////8AAAAAAAAAwAAAAAAAAAAAAQAAAAAAAAAAAAAAAADwPwAAAAAAAAAACQAAAAAAAAAMAAAAAAAAAAYAAAAAAAAAAAAAYDc6yr9cE1iqoHTfPxcAAAAAAAAAAAAAAAAAN0AAAAAAAAAAAAoAAAAAAAAACwAAAAAAAAALAAAAAAAAAAAAADD/rO2/AAAAAAAAzD8IAAAAAAAAAAAAAAAAACBAAAAAAAAAAAD//////////////////////v////////8AAAAAAAAAwAAAAAAAAAAAAQAAAAAAAAAAAAAAAADwPwAAAAAAAAAA//////////////////////7/////////AAAAAAAAAMAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAHEAAAAAAAAAAAA0AAAAAAAAAEAAAAAAAAAAIAAAAAAAAAAAAAHB9hOy/ehSuR+F61D8PAAAAAAAAAAAAAAAAAC5AAAAAAAAAAAAOAAAAAAAAAA8AAAAAAAAABQAAAAAAAAAAAADAns/qPxzHcRzHcdw/AwAAAAAAAAAAAAAAAAAIQAEAAAAAAAAA//////////////////////7/////////AAAAAAAAAMAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAP/////////////////////+/////////wAAAAAAAADAAAAAAAAAAAABAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAARAAAAAAAAABIAAAAAAAAACQAAAAAAAAAAAACw/vzjv+Q4juM4jsM/DAAAAAAAAAAAAAAAAAAoQAAAAAAAAAAA//////////////////////7/////////AAAAAAAAAMAAAAAAAAAAAAEAAAAAAAAAAAAAAAAA8D8AAAAAAAAAAP/////////////////////+/////////wAAAAAAAADAAAAAAAAAAAALAAAAAAAAAAAAAAAAACZAAAAAAAAAAAAUAAAAAAAAABcAAAAAAAAADgAAAAAAAAAAAACwPIndvziuGP2lGds/FwAAAAAAAAAAAAAAAAA3QAAAAAAAAAAAFQAAAAAAAAAWAAAAAAAAAAIAAAAAAAAAAABgSM3f0b8AAAAAAADYPwgAAAAAAAAAAAAAAAAAIEAAAAAAAAAAAP/////////////////////+/////////wAAAAAAAADAAAAAAAAAAAACAAAAAAAAAAAAAAAAAABAAAAAAAAAAAD//////////////////////v////////8AAAAAAAAAwAAAAAAAAAAABgAAAAAAAAAAAAAAAAAYQAAAAAAAAAAAGAAAAAAAAAAZAAAAAAAAAAsAAAAAAAAAAAAAkHQA9j+Iyg5Tl9u/Pw8AAAAAAAAAAAAAAAAALkABAAAAAAAAAP/////////////////////+/////////wAAAAAAAADAAAAAAAAAAAAOAAAAAAAAAAAAAAAAACxAAAAAAAAAAAD//////////////////////v////////8AAAAAAAAAwAAAAAAAAAAAAQAAAAAAAAAAAAAAAADwPwAAAAAAAAAAGwAAAAAAAAAcAAAAAAAAAAoAAAAAAAAAAAAAUEJ6BMAkDwaccS3CPw0AAAAAAAAAAAAAAAAAKkAAAAAAAAAAAP/////////////////////+/////////wAAAAAAAADAAAAAAAAAAAABAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAD//////////////////////v////////8AAAAAAAAAwAAAAAAAAAAADAAAAAAAAAAAAAAAAAAoQAAAAAAAAAAAlGgdjANWNjSUiYiHlFKUKEsDjAF8lE4ojApsZWZ0X2NoaWxklIwLcmlnaHRfY2hpbGSUjAdmZWF0dXJllIwJdGhyZXNob2xklIwIaW1wdXJpdHmUjA5uX25vZGVfc2FtcGxlc5SMF3dlaWdodGVkX25fbm9kZV9zYW1wbGVzlIwSbWlzc2luZ19nb190b19sZWZ0lHSUfZQoaEVoLUsAhpRoRmgtSwiGlGhHaC1LEIaUaEhoHYwCZjiUiYiHlFKUKEsDaCFOTk5K/////0r/////SwB0lGJLGIaUaEloVEsghpRoSmgtSyiGlGhLaFRLMIaUaExoHYwCdTGUiYiHlFKUKEsDaEROTk5K/////0r/////SwB0lGJLOIaUdUtASwFLEHSUYksdhZRoJHSUUpSMBnZhbHVlc5RoGSiW0AEAAAAAAAAAAAAAAADgPwAAAAAAAOA/w6/GRHqg4j96oHJ2C7/aP0YXXXTRRec/dNFFF1100T89z/M8z/PsPxiGYRiGYbg/AAAAAAAAAAAAAAAAAADwP2ZmZmZmZu4/mpmZmZmZqT8AAAAAAADwPwAAAAAAAAAAAAAAAAAAAAAAAAAAAADwPyELWchCFuI/velNb3rT2z8AAAAAAADAPwAAAAAAAOw/AAAAAAAA8D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA8D+amZmZmZnpP5qZmZmZmck/VVVVVVVV1T9VVVVVVVXlPwAAAAAAAAAAAAAAAAAA8D8AAAAAAADwPwAAAAAAAAAAVVVVVVVV7T9VVVVVVVW1PwAAAAAAAAAAAAAAAAAA8D8AAAAAAADwPwAAAAAAAAAAOL3pTW960z9kIQtZyELmPwAAAAAAAOg/AAAAAAAA0D8AAAAAAAAAAAAAAAAAAPA/AAAAAAAA8D8AAAAAAAAAABEREREREbE/3t3d3d3d7T8AAAAAAAAAAAAAAAAAAPA/AAAAAAAA8D8AAAAAAAAAABQ7sRM7sbM/ntiJndiJ7T8AAAAAAADwPwAAAAAAAAAAAAAAAAAAAAAAAAAAAADwP5RoVEsdSwFLAoeUaCR0lFKUdWKMEF9za2xlYXJuX3ZlcnNpb26UjAUxLjguMJR1Yi4="

class DecisionTree:
    """Trained Decision Tree model"""
    
    def __init__(self):
        """Initialize model from saved weights"""
        import pickle
        import base64
        model_data = base64.b64decode(MODEL_PICKLE_B64)
        self.model = pickle.loads(model_data)
    
    def predict(self, X):
        """Make predictions on input data (X should be scaled)"""
        return self.model.predict(X)
    
    def predict_proba(self, X):
        """Get prediction probabilities"""
        return self.model.predict_proba(X)

# Initialize model instance
model = DecisionTree()
